### ISSUE TITLE
Create a help page that explains how to embed a widget into Canvas

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Materia-Docs#8]
The LTI-only Materia page implies some sort of help documentation which only exists right now as part of UCF's Webcourses Support's documentation.

So, we need a page in the github pages site that covers how to do this. It should use screenshots from a non-customized canvas (we can use a canvas docker box as needed).

**Comment by FrenjaminBanklin** [comment]
This page exists, but is out of date.
http://ucfcdl.github.io/Materia/create/embedding-in-canvas.html

**Comment by clpetersonucf** [comment]
Somewhat related, but I left some comments in #186 the other day concerning updates to Materia itself to make the widget embedding process in Canvas more obvious and clear to instructors.

**Comment by iturgeon** [comment]
This issue looks like it was taken care of in an update 9 mo. ago
https://ucfopen.github.io/Materia-Docs/create/embedding-in-canvas.html
